schema_version = "1.0.0"
id = "KHR_physics_rigid_bodies"
name = "glTF Physics Rigid Bodies"
version = "0.6.0"
tagline = "Includes rigid body info when exporting glTF files"
maintainer = "Eoin Mcloughlin"
type = "add-on"
tags = ["Import-Export", "Physics"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/eoineoineoin/glTF_Physics_Blender_Exporter/"
copyright = ["2025 Eoin Mcloughlin, Havok"]
