schema_version = "0.1.0"
id = "KHR_physics_rigid_bodies"
name = "Physics Rigid Bodies"
version = "0.5.0"
tagline = "Plugin for Blender to enable export of rigid body info when exporting glTF files."
maintainer = "Eoin Mcloughlin"
type = "add-on"
permissions = ["files"]
tags = ["Import-Export"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
website = "https://github.com/eoineoineoin/glTF_Physics_Blender_Exporter/"
copyright = ["Eoin Mcloughlin, Havok"]
